name: CI - Main
on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: "Setup Java JDK"
        uses: actions/setup-java@v3.11.0
        with:
          java-version: 17
          distribution: adopt
      - name: Unit Tests
        uses: eskatos/gradle-command-action@5056fa9d50478a14af3c9925c12ca02318659d3e
        with:
          arguments: test
      - name: Codacy Publish
        uses: codacy/codacy-coverage-reporter-action@master
        with:
          project-token: ${{ secrets.CODACY_TOKEN }}

  javadoc:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main' || contains(github.ref, 'refs/tags/')
    steps:
      - uses: actions/checkout@v3
      - name: "Setup Java JDK"
        uses: actions/setup-java@v3.11.0
        with:
          java-version: 17
          distribution: adopt
      - name: Generate javadoc
        uses: eskatos/gradle-command-action@5056fa9d50478a14af3c9925c12ca02318659d3e
        with:
          arguments: globalJavadoc
      - name: Upload javadoc
        uses: sebastianpopp/ftp-action@releases/v2
        with:
          host: ${{ secrets.WEBSPACE_HOST }}
          user: ${{ secrets.WEBSPACE_USER }}
          password: ${{ secrets.WEBSPACE_PASSWORD }}
          localDir: "build/javadoc/"
          remoteDir: "javadoc/"

  documentation:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main' || contains(github.ref, 'refs/tags/')
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - run: pip3 install -r requirements.txt
      - run: mkdocs build -d build/site/
      - name: Upload documentation
        uses: sebastianpopp/ftp-action@releases/v2
        with:
          host: ${{ secrets.WEBSPACE_HOST }}
          user: ${{ secrets.WEBSPACE_USER }}
          password: ${{ secrets.WEBSPACE_PASSWORD }}
          localDir: "build/site/"
          remoteDir: "."
