name: CI - Pull Request
on:
  - pull_request

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v1
        with:
          java-version: 11
      - name: Ktlint
        uses: eskatos/gradle-command-action@v1.3.2
        with:
          arguments: ktlintCheck
      - name: Unit Tests
        uses: eskatos/gradle-command-action@v1.3.2
        with:
          arguments: test
      - name: Codacy Publish
        uses: codacy/codacy-coverage-reporter-action@master
        with:
          project-token: ${{ secrets.CODACY_TOKEN }}

  javadoc:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v1
        with:
          java-version: 11
      - name: Generate javadoc
        uses: eskatos/gradle-command-action@v1.3.2
        with:
          arguments: globalJavadoc

  documentation:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: '3.7'
      - run: pip3 install -r requirements.txt
      - run: mkdocs build -d build/site/
      - name: Upload artifact
        uses: actions/upload-artifact@v1.0.0
        with:
          name: "Website"
          path: "build/site/"
