name: CI
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-java@v1
      with:
        java-version: 11
    - name: Unit Tests
      uses: eskatos/gradle-command-action@v1.3.2
      with:
        arguments: test
    - name: Codacy Publish
      uses: codacy/codacy-coverage-reporter-action@master
      with:
        project-token: ${{ secrets.CODACY_TOKEN }}

  javadoc:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/master' || contains(github.ref, 'refs/tags/')
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v1
        with:
          java-version: 11
      - name: Unit Tests
        uses: eskatos/gradle-command-action@v1.3.2
        with:
          arguments: globalJavadoc
      - name: Upload artifact
        uses: actions/upload-artifact@v1.0.0
        with:
          name: "Javadoc"
          path: "build/javadoc"

  publish:
    runs-on: ubuntu-latest
    needs:
      - build
      - javadoc
#    if: github.event_name == 'push' && contains(github.ref, 'refs/tags/')
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-java@v1
      with:
        java-version: 11
    - name: Build
      uses: eskatos/gradle-command-action@v1.3.2
      env:
        USERNAME: raynigon
        TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        arguments: publish
